development:
  adapter: postgresql
  database: fake_server
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fake_server
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fake_server
  pool: 5
  timeout: 5000